version: '3'
services:


  pet_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./pet_api:/pet_api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=petdb
      - DB_USER=root
      - DB_PASS=12345

    depends_on:
      - db



  db:
    image: mysql:5.7.15
    ports:
      - '3306:3306'

    environment:
      - MYSQL_DATABASE=petdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_PORT=3306

    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

    expose:
      # Opens port 3306 on the container
      - '3306'

    volumes:
      - ./SQLModel.sql:/docker-entrypoint-initdb.d/SQLModel.sql





