# Generated by Django 2.1.5 on 2019-07-12 10:08

from django.db import migrations, models
from pet_api import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('species', models.CharField(blank=True, max_length=45)),
                ('gender', models.CharField(blank=True, choices=[('m', 'männlich'), ('w', 'weiblich')], max_length=1)),
                ('birthday', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'pets',

                'managed': settings.IS_TESTING
            },
        ),
    ]
