# Generated by Django 2.1.5 on 2019-07-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={},
        ),
    ]
